### ISSUE TITLE
The example is not working

### ISSUE THREAD

**Issue by angelo510** [webcat12345/angular-fuse-dashboard#1]
Hi @webcat12345 
I was trying to see the live example of this repo but the github.io link is not working for now.
Can you please figure out the issue and let me know?
Thanks.

**Comment by webcat12345** [comment]
It was deployed on heroku staging but I closed that app for now, you can just try this with your heroku account since all the deploy utilities are ready on repository.

**Comment by Angelo510** [comment]
Why don't you put the README.md file?

**Comment by webcat12345** [comment]
who cares? this is not opensource, it's my own repo. try to take newbie course first before asking such a stupid question. bye
